slack:
  token: "ENTER-YOUR-API-TOKEN-HERE"
default_channel: general
logger:
  enable_private_channel: true
  enable_direct_message: true
database:
  uri: "mongo:27017"
  database: slack_logger
rack:
  secret: "SecureRandom.hex"
